:imagesdir: images/

[[Restcomm_MayDay_SDK]]
= Restcomm MayDay Web SDK 

Mayday application, like the popular Amazon’s feature in their Kindle Fire Tablets is a remote support and instant helpline.
The application is implemented by SPAN on iOS and Android using Telestax’s Restcomm SDK for WebRTC.

==== Prerequisites

•	Restcomm Communications Platform

•	Tomcat 7 and above

•	Restcomm MayDay SDK

==== Restcomm Communications Platform

Install the latest Restcomm Docker image locally (i.e. $ docker pull mobicents/restcomm to get it from docker hub).
For more information please check http://www.telestax.com/rapid-webrtc-application-development-with-restcomm-and-docker/ and https://github.com/RestComm/Restcomm-Docker#restcomm-docker-image. If you aren’t familiar with docker you can have a quick intro here https://www.docker.com/

==== Tomcat 7 and above

Downlaod the latest tomcat from https://tomcat.apache.org/

==== Restcomm MayDay SDK

Once you have installed the Restcomm platform you are ready to start taking advantage of Restcomm’s features from your Web Apps.

Clone the git repository from https://github.com/RestComm/Restcomm-Mayday.git

----
$git clone https://github.com/RestComm/Restcomm-Mayday.git
----

==== To integrate/develop Audio, Video and Chat

Pleae reffer RestComm WebRTC JavaScript SDK - https://github.com/RestComm/webrtcomm/wiki/Restcomm-WebRTComm-Quick-Start


==== To integrate/develop MayDay widget

This widget developed by SPAN and to integrate add the files as mentioned

*Required JavaScript and CSS fiels*

.javascript
----
-   js/jquery.min.js
-   js/jquery.toolbar.js
-   js/jquery-ui.js
----

.css
----
-   css/jquery-ui.css
-   css/documentation.css
-   css/jquery.toolbars.css
-   css/bootstrap.icons.css
----

Copy and Paste the Javascript code - in the file in which you want to integrate the MayDay widget

.javascript
----
jQuery(document).ready(function($) {

				// Define any icon actions before calling the toolbar
				$('#video-panel').on('click', function( event ) {
					//event.preventDefault();
					console.log("click event got triggered!");
					//$('#video-button').toolbar({content: '#video-options', position: 'bottom'});
					$('#dailpad-options').hide();
					$('#video-options').show();
					
				});
				
				$('#hide-video-panel').on('click', function( event ) {
					//event.preventDefault();
					console.log("click event got triggered!");
					//$('#video-button').toolbar({content: '#video-options', position: 'bottom'});
					$('#video-options').hide();
					$('#dailpad-options').hide();
					
				});
				$('#dail-textbox').on('click', function( event ) {
					//event.preventDefault();
					console.log("click event got triggered!");
					//$('#video-button').toolbar({content: '#video-options', position: 'bottom'});
					$('#video-options').hide();
					$('#dailpad-options').show();
					
				});
				
				$('#dest-number').on('click', function( event ) {
					//event.preventDefault();
					console.log("click event got triggered!");
					//$('#video-button').toolbar({content: '#video-options', position: 'bottom'});
					$('#dailpad-options').hide();
					$('#video-options').show();
					
				});
				$('#dest-number').on('click', function( event ) {
					//event.preventDefault();
					console.log("click event got triggered!");
					//$('#video-button').toolbar({content: '#video-options', position: 'bottom'});
					$('#dailpad-options').hide();
					$('#video-options').show();
					
				});
				$('#normal-button').toolbar({content: '#user-options', position: 'top'});
				//$('#video-button').toolbar({content: '#video-options', position: 'bottom'});
				/* $('#normal-button-bottom').toolbar({content: '#user-options', position: 'bottom'});
				$('#normal-button-small').toolbar({content: '#user-options-small', position: 'top', hideOnClick: true});
				$('#button-on-hover').toolbar({content: '#user-options', position: 'top', hover: true});

				$('#button-left').toolbar({content: '#user-options', position: 'left'});
				$('#button-right').toolbar({content: '#user-options', position: 'right'});
				$('#link-toolbar').toolbar({content: '#user-options', position: 'top' }); */
				$("#video-options").draggable();
				$("#video-options").draggable();
				$("#normal-button").draggable();
			});
----

==== To integrate/develop PDF file sharing

This feature enables user to share the pdf file by drag and drop on the screen through Restcomm Datachannel API’s.

*Required JavaScript fiels*

.javascript
----
-	js/pdf.min.js
-	js/span_screenShare.js
----

In span_screenShare.js file search for *_"//CHANGE ME: Specify the PDF share DIV id"_* and provide the PDF file share DIV id.


==== To integrate Co-Browsing

This feature enables co-browsing between the two parties and this developed using third party javascript framework https://togetherjs.com/, by using this one user able to share screen to other and do the annotation through Restcomm Datachannel API's.

*Required fiels*

.javascript
----
-   togetherjs - folder
-   togetherjs/togetherjs-min.js
-   js/cobrowsing.js
-   js/together_canvas.js
----

If running local togetherjs instance then give the local path in

togetherjs-min.js – defaultHubBase=” local path of nodejs server”

If using cloud togetherjs then give dafaultHubBase=” https://hub.togetherjs.com”

For more details about Co-Browsing refer https://togetherjs.com/
